const markers = [
  {
    name: "Los Angeles",
    stadium: "Sofi Stadium",
    coordinates: [-118.25, 34.05],
    dx: -25,
    dy: -15,
    cityX: 65,
    cityY: 0,
    stadiumX: 65,
    stadiumY: 15,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC", // #00CFFF
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-5",
    boxY: "-18",
    boxWidth: "135",
    boxHeight: "43",
  },
  {
    name: "Miami",
    stadium: "Hard Rock Stadium",
    coordinates: [-80.708615, 25.775163],
    dx: 32,
    dy: -10,
    cityX: 87,
    cityY: 18,
    stadiumX: 90,
    stadiumY: 35,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "8",
    boxY: "0",
    boxWidth: "165",
    boxHeight: "47",
  },
  {
    name: "New York",
    stadium: "MetLife Stadium",
    coordinates: [-74.006, 40.7128],
    dx: -25,
    dy: -15,
    cityX: 55,
    cityY: 67,
    stadiumX: 55,
    stadiumY: 85,
    textAnchor: "middle",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-25",
    boxY: "50",
    boxWidth: "160",
    boxHeight: "45",
  },
  {
    name: "Atlanta",
    stadium: "Mercedes-Benz Stadium",
    coordinates: [-84.3877, 33.749],
    dx: -25,
    dy: -15,
    cityX: 110,
    cityY: 30,
    stadiumX: 110,
    stadiumY: 48,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "15",
    boxY: "13",
    boxWidth: "190",
    boxHeight: "45",
  },
  {
    name: "Dallas",
    stadium: "AT&T Stadium",
    coordinates: [-96.8024, 32.7767],
    dx: -25,
    dy: -15,
    cityX: -50,
    cityY: 7,
    stadiumX: -50,
    stadiumY: 22,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-120",
    boxY: "-9",
    boxWidth: "140",
    boxHeight: "38",
  },
  {
    name: "Boston",
    stadium: "Gillette Stadium",
    coordinates: [-71.0589, 42.3601],
    dx: -25,
    dy: -15,
    cityX: 35,
    cityY: -4,
    stadiumX: 35,
    stadiumY: 16,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-40",
    boxY: "-20",
    boxWidth: "150",
    boxHeight: "45",
  },
  {
    name: "Houston",
    stadium: "NRG Stadium",
    coordinates: [-95.3698, 29.7604],
    dx: -25,
    dy: -15,
    cityX: 80,
    cityY: 30,
    stadiumX: 80,
    stadiumY: 47,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "15",
    boxY: "15",
    boxWidth: "130",
    boxHeight: "40",
  },
  {
    name: "Kansas City",
    stadium: "Arrowhead Stadium",
    coordinates: [-94.5786, 39.0922],
    dx: -25,
    dy: -15,
    cityX: -25,
    cityY: -3,
    stadiumX: -22,
    stadiumY: 15,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-105",
    boxY: "-20",
    boxWidth: "165",
    boxHeight: "45",
  },
  {
    name: "Seattle",
    stadium: "Lumen Field",
    coordinates: [-122.3321, 47.6062],
    dx: -55,
    dy: -5,
    cityX: 45,
    cityY: 65,
    stadiumX: 45,
    stadiumY: 82,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-30",
    boxY: "50",
    boxWidth: "150",
    boxHeight: "40",
  },
  {
    name: "Philadelphia",
    stadium: "Lincoln Financial Field",
    coordinates: [-75.1642, 39.9522],
    dx: -25,
    dy: -15,
    cityX: 55,
    cityY: 67,
    stadiumX: 55,
    stadiumY: 85,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-35",
    boxY: "50",
    boxWidth: "177",
    boxHeight: "42",
  },
  {
    name: "SF Bay Area",
    stadium: "Levi's Stadium",
    coordinates: [-122.4194, 37.7749],
    dx: -25,
    dy: -15,
    cityX: 50,
    cityY: -2,
    stadiumX: 50,
    stadiumY: 15,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-30",
    boxY: "-18",
    boxWidth: "160",
    boxHeight: "40",
  },
  {
    name: "New Jersey",
    stadium: "MetLife Stadium",
    coordinates: [-74.4281, 40.0149],
    dx: -25,
    dy: -15,
    cityX: 55,
    cityY: 67,
    stadiumX: 55,
    stadiumY: 85,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0066CC",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-25",
    boxY: "50",
    boxWidth: "160",
    boxHeight: "45",
  },
  {
    name: "Mexico City",
    stadium: "Estadio Azteca",
    coordinates: [-99.0802, 19.48325],
    dx: 70,
    dy: 5,
    cityX: 85,
    cityY: 30,
    stadiumX: 85,
    stadiumY: 48,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0B7F0B",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "12",
    boxY: "15",
    boxWidth: "150",
    boxHeight: "40",
  },
  {
    name: "Guadalajara",
    stadium: "Estadio Akron",
    coordinates: [-103.4442, 20.6663],
    dx: -80,
    dy: 20,
    cityX: -85,
    cityY: 30,
    stadiumX: -85,
    stadiumY: 48,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#006400",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-160",
    boxY: "15",
    boxWidth: "150",
    boxHeight: "40",
  },
  {
    name: "Monterrey",
    stadium: "Estadio BBVA",
    coordinates: [-100.3764, 25.6861],
    dx: -80,
    dy: 0,
    cityX: -85,
    cityY: 30,
    stadiumX: -85,
    stadiumY: 48,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#0B7F0B",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-160",
    boxY: "15",
    boxWidth: "150",
    boxHeight: "40",
  },
  {
    name: "Toronto",
    stadium: "BMO Field",
    coordinates: [-79.3879, 43.6532],
    dx: 25,
    dy: -15,
    cityX: 15,
    cityY: -2,
    stadiumX: 15,
    stadiumY: 15,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#FF0000",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-55",
    boxY: "-18",
    boxWidth: "140",
    boxHeight: "40",
  },
  {
    name: "Vancouver",
    stadium: "BC Place Stadium",
    coordinates: [-123.05, 49.24],
    dx: 25,
    dy: -15,
    cityX: 24,
    cityY: 2,
    stadiumX: 26,
    stadiumY: 17,
    textAnchor: "end",
    alignmentBaseline: "middle",
    connectorProps: {
      stroke: "#DC143C",
      strokeWidth: 2,
      strokeLinecap: "round",
    },
    boxX: "-55",
    boxY: "-15",
    boxWidth: "157",
    boxHeight: "40",
  },
];

export default markers;
